#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x


destroy-cascade() {
  local APP_NAME="$1"
  destroy-cascade-service-type-with-link $APP_NAME "postgres"
  destroy-cascade-service-type-with-link $APP_NAME "redis"
  destroy-cascade-service-type-with-link $APP_NAME "rabbitmq"
  destroy-cascade-service-type-with-link $APP_NAME "mariadb"
  destroy-cascade-service-type-with-link $APP_NAME "mysql"
  destroy-cascade-service-type-with-link $APP_NAME "memcached"
  destroy-cascade-storage $APP_NAME
  echo $APP_NAME | dokku apps:destroy $APP_NAME
}


destroy-cascade-service-type-with-link() {
  # For a service to be able to use this function it needs to support
  # :app-links subcommand
  # :unlink SERVICE_NAME APP_NAME
  # :destroy SERVICE_NAME --force
  local APP_NAME="$1"
  local SERVICE_NAME="$2"
  # Is plugin installed?
  local INSTALLED=`dokku plugin:list | grep $SERVICE_NAME | grep enabled `
  if [[ -z $INSTALLED ]]
  then
     return
  fi
  # Process
  local LINKS=`dokku $SERVICE_NAME:app-links $APP_NAME`
  while IFS= read -r LINK; do
    if [[ ! -z $LINK ]]
    then
      dokku $SERVICE_NAME:unlink $LINK $APP_NAME
      dokku $SERVICE_NAME:destroy $LINK --force
    fi
  done <<< "$LINKS"
}

destroy-cascade-storage() {
  local APP_NAME="$1"
  # Process
  local STORAGES=`dokku storage:list $APP_NAME`
    while IFS= read -r STORAGE; do
      if [[ ! -z $STORAGE ]]
      then
        if [[ ${STORAGE:0:7} != 'website' ]]
        then
          local HOST_DIR="$( echo ${STORAGE%:*} | xargs )"
          local CONTAINER_DIR="$( echo ${STORAGE#*:} | xargs )"
          if [[ ! -z $STORAGE ]]
          then
            dokku storage:unmount $APP_NAME $STORAGE
            # Permissions Problem!!!!!!!!!!!!
            #dokku run $APP_NAME rm -rf "$CONTAINER_DIR/*"
            # Or
            #chown -R "dokku:dokku" "${DOKKU_LIB_ROOT}/data/storage/$HOST_DIR"
            #rm -rf ${DOKKU_LIB_ROOT}/data/storage/$HOST_DIR
          fi
        fi
      fi
    done <<< "$STORAGES"
}